### ISSUE TITLE
Timeout questions

### ISSUE THREAD

**Issue by ayanko** [socketry/async-http#27]
This is interesting lib but I have few questions :)

* What are Async-HTTP default timeouts?
* How I can set up connection timeout ?
* How I can set up read data timeout ?

I could do it with

```ruby
Async do |task|
  response = task.with_timeout(10) do
     endpoint = Async::HTTP::Endpoint.parse(url)
     client = Async::HTTP::Client.new endpoint
     client.get('/')
  end

  body = task.with_timeout(15) do
     response.read
  end
end.wait
```

But it is probably not correct...

**Comment by ioquatix** [comment]
That's reasonable.

However, you should only use timeouts if you need it. Persistent connections will already detect and reconnect if needed. It shouldn't be a user facing issue in most cases. If the underlying TCP connection is still valid, you shouldn't need a timeout on the `response.read` operation. Otherwise, if the response is 1GB, it will surely timeout.

**Comment by ioquatix** [comment]
Let me know if you have more questions, but using `with_timeout` is the correct way. I would suggest putting it around reading each chunk from the body.

**Comment by ayanko** [comment]
But is with_timeout block async one?

**Comment by ioquatix** [comment]
Yes.
